### ISSUE TITLE
bug: multiple positional arguments doesn't work

### ISSUE THREAD

**Issue by balluh** [ndaba1/gommander#21]
**Describe the bug**
When using multiple positional arguments, it fails to parse the arguments after the first one

**Expected behavior**
I'm expecting it to not raise errors when using multiple positional arguments

**Screenshots**
Screenshot of code:
![](https://files.catbox.moe/n6hjdh.png)

Screenshot of output:
![](https://files.catbox.moe/fthhri.png)

**Environment (please complete the following information):**
 - OS: linux
 - Go version: 1.18.3

**Comment by bababoyy** [comment]
Same here.

**Comment by ndaba1** [comment]
Successfully patched in latest release
